/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.multiimages.insertmultiimg.controller;

import com.multiimages.insertmultiimg.InsertMultiImg;
import java.lang.Integer;
import org.springframework.web.multipart.MultipartFile;
import javax.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/insertMultiImg")
public class InsertMultiImgController {

    @Autowired
    private InsertMultiImg insertMultiimg;

    @RequestMapping(value = "/uploadFile", produces = MediaType.APPLICATION_JSON_VALUE, method = RequestMethod.POST)
    public void uploadFile(@RequestParam(value = "relativePath", required = false) Integer relativePath, @RequestPart MultipartFile[] files, HttpServletRequest httpServletRequest) {
        insertMultiimg.uploadFile(relativePath, files, httpServletRequest);
    }
}
